/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'Deliverable 2.Debug+MSP432E401Y' 
 * Target:  'Debug+MSP432E401Y' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "msp.h"



#endif /* RTE_COMPONENTS_H */
